WITH CTE AS (
    SELECT STU.NAME AS N,
    CASE 
    WHEN STU.MARKS BETWEEN GRD.MIN_MARK AND GRD.MAX_MARK THEN GRD.GRADE
    ELSE 0
    END AS COMB,
    STU.MARKS AS M
    FROM STUDENTS AS STU
    JOIN GRADES AS GRD ON STU.MARKS BETWEEN GRD.MIN_MARK AND GRD.MAX_MARK
)
SELECT
CASE
WHEN COMB<8 THEN NULL
ELSE N
END AS NAME,
COMB,
M
FROM CTE
ORDER BY COMB DESC, NAME ASC, M ASC